/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockContract } from './MockContract.js';
export * as factories from './factories/index.js';
export { MockContract__factory } from './factories/MockContract__factory.js';