/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface IntentRelayInterface extends Interface {
    getFunction(nameOrSignature: "cancelIntent" | "getCalldataHandles" | "intents" | "markExecuted" | "nextIntentId" | "noxCompute" | "relayer" | "requestTriggerCheck" | "submitIntent" | "verifyTrigger"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "IntentCancelled" | "IntentExecuted" | "IntentSubmitted" | "IntentTriggered" | "TriggerCheckFailed" | "TriggerCheckRequested"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelIntent', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getCalldataHandles', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'intents', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markExecuted', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextIntentId', values?: undefined): string;
encodeFunctionData(functionFragment: 'noxCompute', values?: undefined): string;
encodeFunctionData(functionFragment: 'relayer', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestTriggerCheck', values: [BigNumberish, BytesLike, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'submitIntent', values: [BytesLike, BigNumberish, BytesLike, BytesLike[], BigNumberish, BytesLike, BytesLike, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'verifyTrigger', values: [BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'cancelIntent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCalldataHandles', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'intents', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markExecuted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextIntentId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'noxCompute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'relayer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestTriggerCheck', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitIntent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyTrigger', data: BytesLike): Result;
  }

  
    export namespace IntentCancelledEvent {
      export type InputTuple = [intentId: BigNumberish];
      export type OutputTuple = [intentId: bigint];
      export interface OutputObject {intentId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentExecutedEvent {
      export type InputTuple = [intentId: BigNumberish];
      export type OutputTuple = [intentId: bigint];
      export interface OutputObject {intentId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentSubmittedEvent {
      export type InputTuple = [intentId: BigNumberish, owner: AddressLike];
      export type OutputTuple = [intentId: bigint, owner: string];
      export interface OutputObject {intentId: bigint, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentTriggeredEvent {
      export type InputTuple = [intentId: BigNumberish, targetHandle: BytesLike, calldataHandles: BytesLike[]];
      export type OutputTuple = [intentId: bigint, targetHandle: string, calldataHandles: string[]];
      export interface OutputObject {intentId: bigint, targetHandle: string, calldataHandles: string[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TriggerCheckFailedEvent {
      export type InputTuple = [intentId: BigNumberish];
      export type OutputTuple = [intentId: bigint];
      export interface OutputObject {intentId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TriggerCheckRequestedEvent {
      export type InputTuple = [intentId: BigNumberish, resultHandle: BytesLike];
      export type OutputTuple = [intentId: bigint, resultHandle: string];
      export interface OutputObject {intentId: bigint, resultHandle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IntentRelay extends BaseContract {
    
    connect(runner?: ContractRunner | null): IntentRelay;
    waitForDeployment(): Promise<this>;

    interface: IntentRelayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelIntent: TypedContractMethod<
      [intentId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getCalldataHandles: TypedContractMethod<
      [intentId: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    intents: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint, bigint, string] & {owner: string, triggerConditionHandle: string, compareOp: bigint, targetHandle: string, calldataLength: bigint, status: bigint, activeCheckHandle: string }],
      'view'
    >
    

    
    markExecuted: TypedContractMethod<
      [intentId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    nextIntentId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    noxCompute: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    relayer: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    requestTriggerCheck: TypedContractMethod<
      [intentId: BigNumberish, currentValueHandle: BytesLike, currentValueOwner: AddressLike, currentValueProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitIntent: TypedContractMethod<
      [triggerConditionHandle: BytesLike, compareOp: BigNumberish, targetHandle: BytesLike, calldataHandles: BytesLike[], calldataLength: BigNumberish, triggerProof: BytesLike, targetProof: BytesLike, calldataProofs: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    verifyTrigger: TypedContractMethod<
      [intentId: BigNumberish, decryptionProof: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelIntent'): TypedContractMethod<
      [intentId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getCalldataHandles'): TypedContractMethod<
      [intentId: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'intents'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, string, bigint, bigint, string] & {owner: string, triggerConditionHandle: string, compareOp: bigint, targetHandle: string, calldataLength: bigint, status: bigint, activeCheckHandle: string }],
      'view'
    >;
getFunction(nameOrSignature: 'markExecuted'): TypedContractMethod<
      [intentId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextIntentId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'noxCompute'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'relayer'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'requestTriggerCheck'): TypedContractMethod<
      [intentId: BigNumberish, currentValueHandle: BytesLike, currentValueOwner: AddressLike, currentValueProof: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitIntent'): TypedContractMethod<
      [triggerConditionHandle: BytesLike, compareOp: BigNumberish, targetHandle: BytesLike, calldataHandles: BytesLike[], calldataLength: BigNumberish, triggerProof: BytesLike, targetProof: BytesLike, calldataProofs: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verifyTrigger'): TypedContractMethod<
      [intentId: BigNumberish, decryptionProof: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'IntentCancelled'): TypedContractEvent<IntentCancelledEvent.InputTuple, IntentCancelledEvent.OutputTuple, IntentCancelledEvent.OutputObject>;
getEvent(key: 'IntentExecuted'): TypedContractEvent<IntentExecutedEvent.InputTuple, IntentExecutedEvent.OutputTuple, IntentExecutedEvent.OutputObject>;
getEvent(key: 'IntentSubmitted'): TypedContractEvent<IntentSubmittedEvent.InputTuple, IntentSubmittedEvent.OutputTuple, IntentSubmittedEvent.OutputObject>;
getEvent(key: 'IntentTriggered'): TypedContractEvent<IntentTriggeredEvent.InputTuple, IntentTriggeredEvent.OutputTuple, IntentTriggeredEvent.OutputObject>;
getEvent(key: 'TriggerCheckFailed'): TypedContractEvent<TriggerCheckFailedEvent.InputTuple, TriggerCheckFailedEvent.OutputTuple, TriggerCheckFailedEvent.OutputObject>;
getEvent(key: 'TriggerCheckRequested'): TypedContractEvent<TriggerCheckRequestedEvent.InputTuple, TriggerCheckRequestedEvent.OutputTuple, TriggerCheckRequestedEvent.OutputObject>;

    filters: {
      
      'IntentCancelled(uint256)': TypedContractEvent<IntentCancelledEvent.InputTuple, IntentCancelledEvent.OutputTuple, IntentCancelledEvent.OutputObject>;
      IntentCancelled: TypedContractEvent<IntentCancelledEvent.InputTuple, IntentCancelledEvent.OutputTuple, IntentCancelledEvent.OutputObject>;
    

      'IntentExecuted(uint256)': TypedContractEvent<IntentExecutedEvent.InputTuple, IntentExecutedEvent.OutputTuple, IntentExecutedEvent.OutputObject>;
      IntentExecuted: TypedContractEvent<IntentExecutedEvent.InputTuple, IntentExecutedEvent.OutputTuple, IntentExecutedEvent.OutputObject>;
    

      'IntentSubmitted(uint256,address)': TypedContractEvent<IntentSubmittedEvent.InputTuple, IntentSubmittedEvent.OutputTuple, IntentSubmittedEvent.OutputObject>;
      IntentSubmitted: TypedContractEvent<IntentSubmittedEvent.InputTuple, IntentSubmittedEvent.OutputTuple, IntentSubmittedEvent.OutputObject>;
    

      'IntentTriggered(uint256,bytes32,bytes32[])': TypedContractEvent<IntentTriggeredEvent.InputTuple, IntentTriggeredEvent.OutputTuple, IntentTriggeredEvent.OutputObject>;
      IntentTriggered: TypedContractEvent<IntentTriggeredEvent.InputTuple, IntentTriggeredEvent.OutputTuple, IntentTriggeredEvent.OutputObject>;
    

      'TriggerCheckFailed(uint256)': TypedContractEvent<TriggerCheckFailedEvent.InputTuple, TriggerCheckFailedEvent.OutputTuple, TriggerCheckFailedEvent.OutputObject>;
      TriggerCheckFailed: TypedContractEvent<TriggerCheckFailedEvent.InputTuple, TriggerCheckFailedEvent.OutputTuple, TriggerCheckFailedEvent.OutputObject>;
    

      'TriggerCheckRequested(uint256,bytes32)': TypedContractEvent<TriggerCheckRequestedEvent.InputTuple, TriggerCheckRequestedEvent.OutputTuple, TriggerCheckRequestedEvent.OutputObject>;
      TriggerCheckRequested: TypedContractEvent<TriggerCheckRequestedEvent.InputTuple, TriggerCheckRequestedEvent.OutputTuple, TriggerCheckRequestedEvent.OutputObject>;
    
    };
  }