/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MockContractInterface extends Interface {
    getFunction(nameOrSignature: "noxCompute" | "registerHandle"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'noxCompute', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerHandle', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'noxCompute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerHandle', data: BytesLike): Result;
  }

  

  export interface MockContract extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockContract;
    waitForDeployment(): Promise<this>;

    interface: MockContractInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    noxCompute: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registerHandle: TypedContractMethod<
      [handle: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'noxCompute'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerHandle'): TypedContractMethod<
      [handle: BytesLike, proof: BytesLike, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }