/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MockSwapContract, MockSwapContractInterface } from "../MockSwapContract.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "executor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "SwapExecuted",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "swap",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5060bf80601a5f395ff3fe6080604052348015600e575f5ffd5b50600436106026575f3560e01c806394b918de14602a575b5f5ffd5b603960353660046073565b603b565b005b60405181815233907fc85f9af794f497ce4710fdc6b8c721dac692ab884e8329f4dddc9d5ae48b8b4b9060200160405180910390a250565b5f602082840312156082575f5ffd5b503591905056fea26469706673582212207d20fa1283092e89d4772ea80252e3f1e3ee1d861b3514cd78798567a58c175964736f6c63430008230033";

  
      type MockSwapContractConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockSwapContractConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockSwapContract__factory extends ContractFactory {
    
      constructor(...args: MockSwapContractConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockSwapContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockSwapContract__factory {
      return super.connect(runner) as MockSwapContract__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockSwapContractInterface {
      return new Interface(_abi) as MockSwapContractInterface;
    }
    
    override attach(address: string | Addressable): MockSwapContract {
      return super.attach(address) as MockSwapContract;
    }
  static connect(address: string, runner?: ContractRunner | null): MockSwapContract {
      return new Contract(address, _abi, runner) as unknown as MockSwapContract;
    }
  }

  
  