/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MockContract, MockContractInterface } from "../MockContract.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_noxCompute",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "noxCompute",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "handle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      }
    ],
    "name": "registerHandle",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506040516102e13803806102e1833981016040819052602b91604e565b5f80546001600160a01b0319166001600160a01b03929092169190911790556079565b5f60208284031215605d575f5ffd5b81516001600160a01b03811681146072575f5ffd5b9392505050565b61025b806100865f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c806316fcf89b1461003857806370c899971461004d575b5f5ffd5b61004b610046366004610143565b61007b565b005b5f5461005f906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b5f5460405163682b8f2160e11b81526001600160a01b039091169063d0571e42906100b39086903390879087906023906004016101ba565b5f604051808303815f87803b1580156100ca575f5ffd5b505af11580156100dc573d5f5f3e3d5ffd5b50505f54604051635ca4b5b160e11b8152600481018790523360248201526001600160a01b03909116925063b9496b6291506044015f604051808303815f87803b158015610128575f5ffd5b505af115801561013a573d5f5f3e3d5ffd5b50505050505050565b5f5f5f60408486031215610155575f5ffd5b83359250602084013567ffffffffffffffff811115610172575f5ffd5b8401601f81018613610182575f5ffd5b803567ffffffffffffffff811115610198575f5ffd5b8660208284010111156101a9575f5ffd5b939660209190910195509293505050565b8581526001600160a01b03851660208201526080604082018190528101839052828460a08301375f60a084830101525f60a0601f19601f86011683010190506064831061021557634e487b7160e01b5f52602160045260245ffd5b826060830152969550505050505056fea26469706673582212202a13345357085ef81286803cd91fc654d0ebf13587e165019581575c26f31a6564736f6c63430008230033";

  
      type MockContractConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockContractConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockContract__factory extends ContractFactory {
    
      constructor(...args: MockContractConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_noxCompute: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_noxCompute, overrides || {});
    };
    override deploy(_noxCompute: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_noxCompute, overrides || {}) as Promise<MockContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockContract__factory {
      return super.connect(runner) as MockContract__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockContractInterface {
      return new Interface(_abi) as MockContractInterface;
    }
    
    override attach(address: string | Addressable): MockContract {
      return super.attach(address) as MockContract;
    }
  static connect(address: string, runner?: ContractRunner | null): MockContract {
      return new Contract(address, _abi, runner) as unknown as MockContract;
    }
  }

  
  