/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MockContract, MockContractInterface } from "../MockContract.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_noxCompute",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "noxCompute",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "handle",
        "type": "bytes32"
      },
      {
        "internalType": "bytes",
        "name": "proof",
        "type": "bytes"
      }
    ],
    "name": "registerHandle",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608034606f57601f61029e38819003918201601f19168301916001600160401b03831184841017607357808492602094604052833981010312606f57516001600160a01b03811690819003606f575f80546001600160a01b03191691909117905560405161021690816100888239f35b5f80fd5b634e487b7160e01b5f52604160045260245ffdfe6080806040526004361015610012575f80fd5b5f905f3560e01c90816316fcf89b1461005d57506370c8999714610034575f80fd5b3461005a578060031936011261005a57546040516001600160a01b039091168152602090f35b80fd5b82346101a65760403660031901126101a6576004359160243567ffffffffffffffff81116101a657366023820112156101a65780600401359067ffffffffffffffff82116101a65736602483830101116101a6575f546001600160a01b0316803b156101a657835f60a4828683976024839863682b8f2160e11b85528d60048601523382860152608060448601528260848601520184840137818101830184905260236064830152601f01601f191681010301925af1801561019b57610188575b508054909182916001600160a01b031690813b15610184578291604483926040519485938492635ca4b5b160e11b845260048401523360248401525af18015610179576101685750f35b81610172916101aa565b61005a5780f35b6040513d84823e3d90fd5b5050fd5b61019491505f906101aa565b5f8261011e565b6040513d5f823e3d90fd5b5f80fd5b90601f8019910116810190811067ffffffffffffffff8211176101cc57604052565b634e487b7160e01b5f52604160045260245ffdfea26469706673582212201eaf95b9af98fe6cf19236c95aa7c1997a75720aacc7bad8d07e0bf67afa969464736f6c63430008230033";

  
      type MockContractConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockContractConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockContract__factory extends ContractFactory {
    
      constructor(...args: MockContractConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_noxCompute: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_noxCompute, overrides || {});
    };
    override deploy(_noxCompute: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_noxCompute, overrides || {}) as Promise<MockContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockContract__factory {
      return super.connect(runner) as MockContract__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockContractInterface {
      return new Interface(_abi) as MockContractInterface;
    }
    
    override attach(address: string | Addressable): MockContract {
      return super.attach(address) as MockContract;
    }
  static connect(address: string, runner?: ContractRunner | null): MockContract {
      return new Contract(address, _abi, runner) as unknown as MockContract;
    }
  }

  
  