/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MockSwapContract, MockSwapContractInterface } from "../MockSwapContract.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "executor",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "SwapExecuted",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "swap",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346013576099908160188239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c6394b918de146023575f80fd5b34605f576020366003190112605f5760043581527fc85f9af794f497ce4710fdc6b8c721dac692ab884e8329f4dddc9d5ae48b8b4b60203392a2005b5f80fdfea2646970667358221220ca0c70b8c6da97f106d903c2d0cdd342c890a04a3576c1a870f6cfcaf094a9af64736f6c63430008230033";

  
      type MockSwapContractConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockSwapContractConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockSwapContract__factory extends ContractFactory {
    
      constructor(...args: MockSwapContractConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockSwapContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockSwapContract__factory {
      return super.connect(runner) as MockSwapContract__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockSwapContractInterface {
      return new Interface(_abi) as MockSwapContractInterface;
    }
    
    override attach(address: string | Addressable): MockSwapContract {
      return super.attach(address) as MockSwapContract;
    }
  static connect(address: string, runner?: ContractRunner | null): MockSwapContract {
      return new Contract(address, _abi, runner) as unknown as MockSwapContract;
    }
  }

  
  